# Base URL
baseurl:

# Site live URL
#url: "http://jeremynealbrown.github.io"

# Localhost
url: ./

# Google Analytics key, leave blank to ignore
google_analytics_key: UA-65964466-1

# Name of the site
name: jeremynealbrown.com

# 'meta_description:' Write a description for your new site here.
# It will appear in your document head meta (for Google search results) and in your feed.xml site description.
meta_description: > #
 I am a creative technologist living in Portland, Oregon and working
 for an experience design and software shop called Upswell.

# Site description, used in feed.xml
description: The personal site of Jeremy Neal Brown, a creative technologist from Portland, Oregon

# Site author information
author:
    name: Jeremy Brown
    email: jeremynealbrown@gmail.com
    url: http://jeremynealbrown.github.io

# Social links
social:
    github: jeremynealbrown
    twitter: jeremynealbrown
    gplus: +JeremyBrownFromEarth

# Conversion / Build settings
markdown: kramdown

# This is how you put pygments config in jekyll 2.0 instead of pygments: true
highlighter: pygments

# Permalinks
permalink: pretty

# Extra dirs to include in build
include: [_pages]

collections:
  projects:
      output: true
      permalink: /projects/:path/
  work:
      output: true
      permalink: /work/:path/

exclude:
    - src
    - CNAME
    - Gemfile
    - packages
    - Rakefile
    - README.md
    - .gitignore
    - .sass-cache
    - Gemfile.lock
    - node_modules
    - twitter

# Sass conversion configs
sass:
    sass_dir: assets/css/_sass
    style: :compressed
