# Base URL
baseurl: 

# Site live URL
url: http://jeremyfromearth.github.io

# Google Analytics key, leave blank to ignore
google_analytics_key: UA-65964466-1

# Name of the site
name: JeremyFromEarth

# 'meta_description:' Write a description for your new site here.
# It will appear in your document head meta (for Google search results) and in your feed.xml site description.
meta_description: Freelance software engineer with experience in graphics, networking, machine learning and interactive installations  

# Site description, used in feed.xml
description: The personal site of Jeremy Neal Brown, a creative technologist from Portland, Oregon

# Site author information
author:
    name: Jeremy Brown
    email: jeremy.from.earth@gmail.com
    url: http://jeremynealbrown.github.io

# Social links
social:
    github: jeremynealbrown
    twitter: JeremyFromEarth
    vimeo: JeremyFromEarth

# Conversion / Build settings
markdown: kramdown

# This is how you put pygments config in jekyll 2.0 instead of pygments: true
highlighter: rouge

# Permalinks
permalink: pretty

plugins: 
  - jekyll-gist

# Extra dirs to include in build
include: [_pages]

exclude:
    - src
    - util
    - CNAME
    - Gemfile
    - packages
    - Rakefile
    - README.md
    - .gitignore
    - .sass-cache
    - Gemfile.lock
    - node_modules
    - twitter
    - vendor

# Sass conversion configs
sass:
    sass_dir: assets/css/_sass
    style: :compressed
