encoding: UTF-8
name: JeremyFromEarth
title: JeremyFromEarth
url: http://jeremyfromearth.github.io
google_analytics_key: UA-65964466-1
meta_description: Software Engineer with experience in graphics, networking, machine learning and interactive installations  
description: The personal site of Jeremy Brown, a Software Engineer and musician from Portland, Oregon
author:
  name: Jeremy Brown
  email: jeremynealbrown@gmail.com
  url: http://jeremyfromearth.com
social:
  github: jeremyfromearth
  twitter: JeremyFromEarth
  vimeo: JeremyFromEarth
markdown: kramdown
kramdown:
  smart_quotes:  ["apos", "apos", "ldquo", "rdquo"]
highlighter: rouge
permalink: pretty
plugins: 
  - jekyll-gist
collections:
  work:
    output: true
    permalink: /work/:path/
include: [_pages]
exclude:
  - src
  - util
  - CNAME
  - Gemfile
  - packages
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock
  - node_modules
sass:
  sass_dir: assets/css/_sass
  style: :compressed
