# Site settings
title: things that make things that make
description: > # this means to ignore newlines until "baseurl:"
  I am a creative technologist currently residing in Portland, 
  Oregon and working as a Software Developer at Upswell. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jeremynealbrown.github.io" # the base hostname & protocol for your site
twitter_username: jeremynealbrown
github_username:  jeremynealbrown

# Build settings
markdown: kramdown
